# Generated by Django 2.1 on 2018-08-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='IPAPP',
        ),
    ]
